n: str= input('Digite algo: ')
print(type(n))
print('É um numero?', n.isnumeric())
print('Tem apenas espaços?', n.isspace())
print('É alfabetico?', n.isalpha())
print('É alfanumerico?', n.isalnum())
print('Esta em maiuscula?', n.isupper())
print('Esta em minuscula?', n.islower())
print('Esta capitalizada?', n.istitle())
