Numero= int(input('Digite um numero para a tabuada: '))
print('-'*12)
print('{} x {:2} = {}'.format(Numero, 1, Numero*1))
print('{} x {:2} = {}'.format(Numero, 2, Numero*2))
print('{} x {:2} = {}'.format(Numero, 3, Numero*3))
print('{} x {:2} = {}'.format(Numero, 4, Numero*4))
print('{} x {:2} = {}'.format(Numero, 5, Numero*5))
print('{} x {:2} = {}'.format(Numero, 6, Numero*6))
print('{} x {:2} = {}'.format(Numero, 7, Numero*7))
print('{} x {:2} = {}'.format(Numero, 8, Numero*8))
print('{} x {:2} = {}'.format(Numero, 9, Numero*9))
print('{} x {:2} = {}'.format(Numero, 10, Numero*10))
print('-'*12)

